<?php $films = $this->getViewModel()->getAllFilms(); ?>

<div class="field film required" >
    <h4><?= __('Favourite Film'); ?></h4>
    <div class="control">
        <select id="favourite_film" name="favourite_film">
            <?php foreach ($films as $film): ?>
                <?php if ($film->getStatus() == 1): ?>
                    <option value="<?= $film->getId(); ?>"
                            label="<?= $film->getTitle(); ?>">
                    </option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>
    </div>
</div>
