<?php
$films = $this->getViewModel()->getAllFilms();


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$customerId = $customerSession->getCustomer()->getId();
$customerFavouriteFilm = $customerSession->getCustomer()->getData();

?>

<h1>Favourite Film</h1>

<?php foreach ($films as $film): ?>
    <?php if ($film->getId() == $customerFavouriteFilm['favourite_film']): ?>
        <p><?= $film->getTitle(); ?></p>
    <?php endif; ?>
<?php endforeach; ?>
